version: 0.2

env: 
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPOSITORY: "tomcat-petclinic"
    ECR_TOKEN_PARAMETER: "/ecr/ECR_TOKEN"
phases:
  pre_build:
    commands:
      - echo "Getting ECR token from Parameter Store..."
      - ECR_TOKEN=$(aws ssm get-parameter --name "$ECR_TOKEN_PARAMETER" --with-decryption --query 'Parameter.Value' --output text)
      - echo "$ECR_TOKEN" | docker login --username AWS --password-stdin 633160612874.dkr.ecr.us-east-1.amazonaws.com
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com 
      - REPOSITORY_URI=${ECR_URI}/${ECR_REPOSITORY}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Repository- ${REPOSITORY_URI}"
      - echo "Image tag - ${IMAGE_TAG}"


  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."
      - docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} .
      - docker tag ${REPOSITORY_URI}:${IMAGE_TAG} ${REPOSITORY_URI}:latest

  
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest   
