version: 0.2

env: 
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    AWS_ACCOUNT_NO: "633160612874"
    DOCKER_REGISTRY: "dkr.ecr.us-east-2.amazonaws.com"
    ECR_REPOSITORY: "tomcat-petclinic"
phases:
  pre_build:
    commands:
     - ls -lrtha

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."
      - docker build -t ${AWS_ACCOUNT_NO}.${DOCKER_REGISTRY}/${ECR_REPOSITORY}:${CODEBUILD_BUILD_NUMBER} .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_NO}.${DOCKER_REGISTRY}/${ECR_REPOSITORY}
      - docker push ${AWS_ACCOUNT_NO}.${DOCKER_REGISTRY}/${ECR_REPOSITORY}:${CODEBUILD_BUILD_NUMBER}
