version: 0.2

env: 
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPOSITORY: "tomcat-petclinic"
phases:
  pre_build:
    commands:
     - ./mvnw install
     - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 633160612874.dkr.ecr.us-east-2.amazonaws.com/tomcat-petclinic

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."
      - docker build -t 633160612874.dkr.ecr.us-east-2.amazonaws.com/tomcat-petclinic .
      - docker tag 633160612874.dkr.ecr.us-east-2.amazonaws.com/tomcat-petclinic:latest

  
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 633160612874.dkr.ecr.us-east-2.amazonaws.com/tomcat-petclinic
      - docker push 633160612874.dkr.ecr.us-east-2.amazonaws.com/tomcat-petclinic:latest
