version: 0.0
os: linux
files:
  - source: /spring-petclinic-3.3.0-SNAPSHOT.jar
    destination: /opt/tomcat/webapps
hooks:
   ApplicationStop:
     - location: scripts/tomcat-stop.sh
       timeout: 300
       runas: root

  ApplicationInstall:
      - location: scripts/tomcat-install.sh
        timeout: 300
        runas: root

ApplicationStart:
      - location: scripts/tomcat-start.sh
        timeout: 300
        runas: root
    
